spring.application.name=lectorDeHuella

spring.datasource.url=jdbc:sqlserver://dbsqlhuella.database.windows.net:1433;database=dbPrestamos
spring.datasource.username=Chong
spring.datasource.password=Saltamontes1.
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jackson.serialization.write-dates-as-timestamps=false